import {
  LOGIN_TRANSACTION_TTL_MS,
  LOGIN_TRANSACTION_VERSION,
  OIDC_SESSION_VERSION,
  buildRefreshedOidcSession,
  getAuthorizationResponseParams,
  getIssuerIdentifier,
  getLoginTransactionStorageKey,
  getOidcSessionStorageKey,
  isAuthOperationCurrent,
  isRetryablePreResponseRefreshError,
  isValidOAuthState,
  parseLoginTransaction,
  parseStoredOidcSession,
  removeStorageValueIfMatches,
  replaceStorageValueIfMatches,
  resolveAuthenticatedUser,
  setStorageValue,
} from "../security-state";
import type { OidcIdentityMetadata } from "@guardhouse/core";
import type { OidcSessionData, StorageAdapter } from "../types";
import { InMemoryStorageAdapter } from "../utils";

const authority = "https://tenant.guardhouse.test/";
const clientId = "react-client";
const state = "abcdefghijklmnopqrstuvwx";
const identity: OidcIdentityMetadata = {
  issuer: authority,
  clientId,
  subject: "user-1",
  audiences: [clientId],
  authorizedParty: null,
  issuedAt: 1_700_000_000,
  expiresAt: 2_000_000_000,
  nonce: "nonce-value-1234",
  authTime: 1_700_000_000,
  acr: null,
  amr: [],
  sessionId: null,
};

describe("client-bound OIDC storage", () => {
  it("preserves exact issuer identifiers and isolates clients and issuers", () => {
    expect(getIssuerIdentifier(authority)).toBe(authority);
    expect(getOidcSessionStorageKey(authority, clientId)).toBe(
      getOidcSessionStorageKey("https://tenant.guardhouse.test", clientId),
    );
    expect(getOidcSessionStorageKey(authority, clientId)).not.toBe(
      getOidcSessionStorageKey(authority, "other-client"),
    );
    expect(getOidcSessionStorageKey(authority, clientId)).not.toBe(
      getOidcSessionStorageKey("https://other.guardhouse.test", clientId),
    );
  });

  it("rejects legacy and cross-client sessions", () => {
    const session: OidcSessionData = {
      version: OIDC_SESSION_VERSION,
      clientId,
      accessToken: "access-token",
      tokenType: "Bearer",
      expiresAt: 2_000_000_000,
      idToken: "signed-id-token",
      scope: "openid profile",
      identity,
      oidc: { issuer: getIssuerIdentifier(authority) },
    };

    expect(
      parseStoredOidcSession(JSON.stringify(session), authority, clientId),
    ).toEqual(session);
    expect(
      parseStoredOidcSession(
        JSON.stringify({ ...session, version: undefined }),
        authority,
        clientId,
      ),
    ).toBeNull();
    expect(
      parseStoredOidcSession(
        JSON.stringify(session),
        authority,
        "other-client",
      ),
    ).toBeNull();
    expect(
      parseStoredOidcSession(
        JSON.stringify({ ...session, identity: { ...identity, subject: "" } }),
        authority,
        clientId,
      ),
    ).toBeNull();
  });

  it("never restores serialized user or role claims", () => {
    const session: OidcSessionData = {
      version: OIDC_SESSION_VERSION,
      clientId,
      accessToken: "access-token",
      tokenType: "Bearer",
      expiresAt: 2_000_000_000,
      idToken: "signed-id-token",
      scope: "openid profile",
      identity,
      oidc: { issuer: getIssuerIdentifier(authority) },
    };

    const restored = parseStoredOidcSession(
      JSON.stringify({
        ...session,
        user: { sub: "user-1", roles: ["forged-admin"] },
      }),
      authority,
      clientId,
    );

    expect(restored).toEqual(session);
    expect(restored).not.toHaveProperty("user");
  });
});

describe("authorization response recognition", () => {
  it("accepts only the high-entropy state shape generated by core", () => {
    expect(isValidOAuthState(state)).toBe(true);
    expect(isValidOAuthState("too-short")).toBe(false);
    expect(isValidOAuthState(`${state}%`)).toBe(false);
  });

  it("detects mixed-channel pollution and front-channel tokens", () => {
    const mixed = getAuthorizationResponseParams(
      `https://app.test/callback?code=abc&state=${state}#id_token=forged`,
    );
    expect(mixed).toMatchObject({
      source: "query",
      stateCandidates: [state],
      hasMixedChannelParameters: true,
      hasFrontChannelTokens: false,
    });

    const implicit = getAuthorizationResponseParams(
      `https://app.test/callback#access_token=forged&state=${state}`,
    );
    expect(implicit).toMatchObject({
      source: "fragment",
      stateCandidates: [state],
      hasFrontChannelTokens: true,
    });
  });

  it("preserves duplicate and cross-channel state candidates for Core validation", () => {
    expect(
      getAuthorizationResponseParams(
        `https://app.test/callback?code=abc&state=${state}&state=other-valid-state-1234#state=fragment-valid-state-1234`,
      ),
    ).toMatchObject({
      source: "query",
      stateCandidates: [
        state,
        "other-valid-state-1234",
        "fragment-valid-state-1234",
      ],
      hasMixedChannelParameters: true,
    });
  });

  it("does not classify ordinary state parameters as callbacks", () => {
    expect(
      getAuthorizationResponseParams(
        `https://app.test/orders?state=${state}&status=paid`,
      ),
    ).toBeNull();
  });
});

describe("atomic login transactions", () => {
  const now = 1_800_000_000_000;
  const transaction = {
    version: LOGIN_TRANSACTION_VERSION,
    issuer: getIssuerIdentifier(authority),
    clientId,
    redirectUri: "https://app.test/callback",
    state,
    codeVerifier: "v".repeat(43),
    codeChallenge: "c".repeat(43),
    nonce: "nonce-value-1234",
    requestedScope: "openid profile",
    requestedResources: [],
    requiredAcrValues: [],
    requiredAmrValues: [],
    responseMode: "query" as const,
    createdAt: now,
    expiresAt: now + LOGIN_TRANSACTION_TTL_MS,
    issRequired: true,
  };

  it("keys transactions by issuer, client, and returned state", () => {
    expect(getLoginTransactionStorageKey(authority, clientId, state)).not.toBe(
      getLoginTransactionStorageKey(authority, clientId, `${state}a`),
    );
  });

  it("preserves the original redirect URI and enforces exact binding", () => {
    expect(
      parseLoginTransaction(
        JSON.stringify(transaction),
        authority,
        clientId,
        state,
        now + 1,
      ),
    ).toEqual(transaction);
    expect(
      parseLoginTransaction(
        JSON.stringify(transaction),
        authority,
        "other-client",
        state,
        now + 1,
      ),
    ).toBeNull();
  });

  it("rejects expired transaction records", () => {
    expect(
      parseLoginTransaction(
        JSON.stringify(transaction),
        authority,
        clientId,
        state,
        transaction.expiresAt,
      ),
    ).toBeNull();
  });
});

describe("auth operation epoch guard", () => {
  it("accepts only the current epoch in the current client namespace", () => {
    expect(isAuthOperationCurrent(4, 4, "tenant:client", "tenant:client")).toBe(
      true,
    );
    expect(isAuthOperationCurrent(3, 4, "tenant:client", "tenant:client")).toBe(
      false,
    );
    expect(isAuthOperationCurrent(4, 4, "tenant:old", "tenant:new")).toBe(
      false,
    );
  });

  it("stale cleanup cannot delete a newer winning session", async () => {
    const storage = new InMemoryStorageAdapter();
    const key = "gh:v2:session:tenant:client";
    const staleSession = JSON.stringify({ accessToken: "stale" });
    const newerSession = JSON.stringify({ accessToken: "newer" });

    await storage.setItem(key, staleSession);
    await storage.removeItem(key);
    await storage.setItem(key, newerSession);

    await expect(
      removeStorageValueIfMatches(storage, key, staleSession),
    ).resolves.toBe(false);
    await expect(storage.getItem(key)).resolves.toBe(newerSession);
  });

  it("serializes the same namespace key across distinct adapter objects", async () => {
    const backend = new Map<string, string>();
    const key = "gh:v3:session:shared-tenant:shared-client";
    const staleSession = JSON.stringify({ accessToken: "stale" });
    const newerSession = JSON.stringify({ accessToken: "newer" });
    let signalRemovalStarted!: () => void;
    let allowRemoval!: () => void;
    const removalStarted = new Promise<void>((resolve) => {
      signalRemovalStarted = resolve;
    });
    const removalGate = new Promise<void>((resolve) => {
      allowRemoval = resolve;
    });
    const firstAdapter: StorageAdapter = {
      async getItem(storageKey) {
        return backend.get(storageKey) ?? null;
      },
      async setItem(storageKey, value) {
        backend.set(storageKey, value);
      },
      async removeItem(storageKey) {
        signalRemovalStarted();
        await removalGate;
        backend.delete(storageKey);
      },
    };
    const secondAdapter: StorageAdapter = {
      async getItem(storageKey) {
        return backend.get(storageKey) ?? null;
      },
      async setItem(storageKey, value) {
        backend.set(storageKey, value);
      },
      async removeItem(storageKey) {
        backend.delete(storageKey);
      },
    };

    backend.set(key, staleSession);
    const cleanup = removeStorageValueIfMatches(
      firstAdapter,
      key,
      staleSession,
    );
    await removalStarted;
    const newerWrite = setStorageValue(secondAdapter, key, newerSession);
    allowRemoval();

    await expect(cleanup).resolves.toBe(true);
    await expect(newerWrite).resolves.toBeUndefined();
    expect(backend.get(key)).toBe(newerSession);
  });

  it("treats a failed CAS that leaves the expected record as a storage failure", async () => {
    const storage: StorageAdapter = {
      async getItem() {
        return "expected";
      },
      async setItem() {},
      async removeItem() {},
      compareAndRemoveItem() {
        return false;
      },
    };

    await expect(
      removeStorageValueIfMatches(storage, "session-key", "expected"),
    ).rejects.toThrow("Failed to remove persisted authentication state");
  });

  it("never replaces a newer winner through another adapter", async () => {
    const backend = new Map<string, string>();
    const key = "gh:v3:session:shared-tenant:shared-client";
    const staleSession = JSON.stringify({ accessToken: "stale" });
    const refreshedStaleSession = JSON.stringify({
      accessToken: "stale-refreshed",
    });
    const newerSession = JSON.stringify({ accessToken: "newer" });
    const createAdapter = (): StorageAdapter => ({
      async getItem(storageKey) {
        return backend.get(storageKey) ?? null;
      },
      async setItem(storageKey, value) {
        backend.set(storageKey, value);
      },
      async removeItem(storageKey) {
        backend.delete(storageKey);
      },
      compareAndSetItem(storageKey, expectedValue, value) {
        if (backend.get(storageKey) !== expectedValue) return false;
        backend.set(storageKey, value);
        return true;
      },
    });
    const staleAdapter = createAdapter();
    const winnerAdapter = createAdapter();

    backend.set(key, staleSession);
    await winnerAdapter.setItem(key, newerSession);

    await expect(
      replaceStorageValueIfMatches(
        staleAdapter,
        key,
        staleSession,
        refreshedStaleSession,
      ),
    ).resolves.toBe(false);
    expect(backend.get(key)).toBe(newerSession);
  });

  it("treats a failed replace CAS that leaves the expected record as a storage failure", async () => {
    const storage: StorageAdapter = {
      async getItem() {
        return "expected";
      },
      async setItem() {},
      async removeItem() {},
      compareAndSetItem() {
        return false;
      },
    };

    await expect(
      replaceStorageValueIfMatches(
        storage,
        "session-key",
        "expected",
        "replacement",
      ),
    ).rejects.toThrow("Failed to replace persisted authentication state");
  });
});

describe("pre-response refresh failure classification", () => {
  it.each(["NETWORK_ERROR", "REQUEST_TIMEOUT", "OIDC_METADATA_REQUEST_FAILED"])(
    "allows retry only for the known transient error %s",
    (code) => {
      expect(isRetryablePreResponseRefreshError({ code })).toBe(true);
    },
  );

  it.each([
    "INVALID_GRANT",
    "ID_TOKEN_VALIDATION_FAILED",
    "INVALID_IDENTITY",
    "SCOPE_ESCALATION_DETECTED",
    "OIDC_DISCOVERY_FAILED",
  ])("fails closed for the non-retryable error %s", (code) => {
    expect(isRetryablePreResponseRefreshError({ code })).toBe(false);
  });

  it("fails closed for unclassified errors", () => {
    expect(isRetryablePreResponseRefreshError(new Error("offline"))).toBe(
      false,
    );
  });
});

describe("verified OIDC identity", () => {
  const verifiedPayload = {
    sub: "user-1",
    name: "ID token name",
    iss: authority,
    aud: clientId,
    exp: 2_000_000_000,
    iat: 1_700_000_000,
  };

  it("fails closed when UserInfo is unavailable", async () => {
    const userInfoError = new Error("UserInfo unavailable");

    await expect(
      resolveAuthenticatedUser(verifiedPayload, async () => {
        throw userInfoError;
      }),
    ).rejects.toBe(userInfoError);
  });

  it("enriches verified identity only when UserInfo subject matches", async () => {
    await expect(
      resolveAuthenticatedUser(verifiedPayload, async () => ({
        sub: "user-1",
        name: "UserInfo name",
        email: "user@example.com",
      })),
    ).resolves.toEqual({
      user: {
        ...verifiedPayload,
        name: "UserInfo name",
        email: "user@example.com",
      },
    });

    await expect(
      resolveAuthenticatedUser(verifiedPayload, async () => ({
        sub: "another-user",
      })),
    ).rejects.toThrow("UserInfo subject does not match");
  });

  it("deeply detaches and freezes roles and custom claims", async () => {
    const signedClaim = { methods: ["passkey"] };
    const roles = ["reader"];
    const customClaim = { teams: [{ id: "team-1" }] };
    const resolution = await resolveAuthenticatedUser(
      { ...verifiedPayload, signedClaim },
      async () => ({
        sub: "user-1",
        roles,
        customClaim,
      }),
    );

    signedClaim.methods.push("password");
    roles.push("admin");
    customClaim.teams[0].id = "attacker-team";

    expect(resolution.user).toMatchObject({
      roles: ["reader"],
      signedClaim: { methods: ["passkey"] },
      customClaim: { teams: [{ id: "team-1" }] },
    });
    expect(Object.isFrozen(resolution.user)).toBe(true);
    expect(Object.isFrozen(resolution.user.roles)).toBe(true);
    expect(Object.isFrozen(resolution.user["signedClaim"])).toBe(true);
    expect(
      Object.isFrozen(
        (resolution.user["customClaim"] as { teams: unknown[] }).teams[0],
      ),
    ).toBe(true);
    expect(() =>
      (resolution.user.roles as string[] | undefined)?.push("owner"),
    ).toThrow();
  });

  it("retains the established identity when refresh omits an ID token", () => {
    const session = {
      version: OIDC_SESSION_VERSION,
      clientId,
      accessToken: "old-access-token",
      tokenType: "Bearer",
      expiresAt: 900,
      refreshToken: "old-refresh-token",
      idToken: "expired-but-previously-verified-id-token",
      scope: "openid profile",
      identity,
      oidc: { issuer: getIssuerIdentifier(authority) },
    };

    expect(
      buildRefreshedOidcSession(
        session,
        {
          access_token: "new-access-token",
          refresh_token: "new-refresh-token",
          token_type: "Bearer",
          expires_in: 3600,
        },
        identity,
        1_000,
      ),
    ).toEqual({
      ...session,
      accessToken: "new-access-token",
      refreshToken: "new-refresh-token",
      expiresAt: 4_600,
    });
  });
});
