export const GuardhouseConstants = {
  Endpoints: {
    WellKnownOpenIdConfiguration: ".well-known/openid-configuration",
    WellKnownJwks: ".well-known/jwks.json",
    ConnectToken: "connect/token",
    ConnectIntrospect: "connect/introspect",
    ConnectAuthorize: "connect/authorize",
  },
  Algorithms: {
    RS256: "RS256",
    RS384: "RS384",
    RS512: "RS512",
    ES256: "ES256",
    ES384: "ES384",
    ES512: "ES512",
    PS256: "PS256",
    PS384: "PS384",
    PS512: "PS512",
    None: "none",
  },
  TokenTypes: {
    Jwt: "JWT",
  },
  Headers: {
    Authorization: "Authorization",
    BearerPrefix: "Bearer ",
    WwwAuthenticate: "WWW-Authenticate",
    ContentType: "Content-Type",
  },
  JwtClaims: {
    Type: "typ",
    Algorithm: "alg",
    KeyId: "kid",
    Issuer: "iss",
    Audience: "aud",
    Subject: "sub",
    Expiration: "exp",
    IssuedAt: "iat",
    NotBefore: "nbf",
    JwtId: "jti",
    Scope: "scope",
    ClientId: "client_id",
    TokenType: "token_type",
    AuthorizedParty: "azp",
  },
  Defaults: {
    JwksCacheDurationHours: 24,
    JwksRefreshIntervalMinutes: 5,
    CacheExpirationBufferSeconds: 60,
    RequestTimeoutSeconds: 30,
    MaxRetryAttempts: 3,
    ClockSkewMinutes: 5,
    DefaultScope: "api",
    IntrospectionCacheTtlSeconds: 5,
    MaxTokenLengthBytes: 8192,
    MaxTokenAgeSeconds: 31536000,
  },
  Validation: {
    ValidateIssuer: true,
    ValidateAudience: true,
    ValidateLifetime: true,
    ValidateIssuerSigningKey: true,
  },
  ContentTypes: {
    Json: "application/json",
    JwkSet: "application/jwk-set+json",
  },
  Schemes: {
    Https: "https:",
    Http: "http:",
  },
  ErrorMessages: {
    GenericUnauthorized: "Unauthorized",
    InvalidToken: "Invalid or expired token",
    MissingAuthorization: "Authorization header is required",
  },
};
